<?php

namespace Tests\Feature;

use App\Models\User;
use Auth;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserTest extends TestCase
{
    private $user;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testAccessAdmin()
    {
        $this->user->role = 'admin';
        Auth::login($this->user);

        $response = $this->get('/user');

        $response->assertStatus(200);
    }

    public function testAccessMaster()
    {
        $this->user->role = 'master';
        Auth::login($this->user);

        $response = $this->get('/user');

        $response->assertStatus(200);
    }

    public function testAccessMasterProvider()
    {
        $this->user->role = 'master_provider';
        Auth::login($this->user);

        $response = $this->get('/user');

        $response->assertStatus(302);
    }

    public function testAccessSubMasterProvider()
    {
        $this->user->role = 'sub_master_provider';
        Auth::login($this->user);

        $response = $this->get('/user');

        $response->assertStatus(302);
    }
}
